services:
  - type: web
    name: gymtrack-api
    runtime: docker
    dockerfilePath: gym-backend/Dockerfile
    dockerContext: gym-backend
    plan: free
    healthCheckPath: 
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prods