services:
  - type: web
    name: gymtrack-api
    runtime: docker
    rootDir: gym-backend
    dockerfilePath: ./Dockerfile ✅
    plan: free
    healthCheckPath: /exercise/all
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false